# Codemagic CI/CD Configuration for Bro App
# Docs: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/

workflows:
  # ============================================
  # ANDROID - Google Play Store
  # ============================================
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - google_play_credentials
        - keystore_credentials
      flutter: stable
      java: 17
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'release/*'
          include: true
        - pattern: 'main'
          include: true
      
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_BUILD_DIR/keystore.jks
          EOF
          
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build APK (debug for testing)
        script: flutter build apk --debug
        
      - name: Build AAB (release for Play Store)
        script: flutter build appbundle --release
        
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  # ============================================
  # iOS - TestFlight / App Store
  # ============================================
  ios-release:
    name: iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Bro App
      
    environment:
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.bro.mobile
      flutter: stable
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'release/*'
          include: true
        - pattern: 'main'
          include: true
          
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
        
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          
      - name: Build iOS
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
        
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # DEBUG BUILD (para testes)
  # ============================================
  debug-build:
    name: Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      java: 17
      
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
          
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Analyze code
        script: flutter analyze --no-fatal-infos
        
      - name: Build Android Debug
        script: flutter build apk --debug
        
    artifacts:
      - build/**/outputs/**/*.apk
